### PR TITLE
Remove Dark Sky support and fix an issue with Tempest and an issue with Open Weather Map.

### PR DESCRIPTION
**Pull request by dacarson**
Dark Sky no longer exists, so remove support for it (#267)
Fix error that is reported when no Tempest weather station data is received (#275)
Unrelated to Tempest weather station, also fix Open Weather Map crash when using API 2.5 (#271)

### CODE REVIEW

**Comment by wimleers** [comment]
Testing this locally (`git clone …` followed by `npm link` and a Homebridge restart), yields the following result:
```
[12/29/2023, 10:20:57 PM] ERROR LOADING PLUGIN homebridge-weather-plus:
[12/29/2023, 10:20:57 PM] Error: Cannot find module 'request'
Require stack:
- /Users/admin/Desktop/homebridge-weather-plus/apis/weatherunderground.js
- /Users/admin/Desktop/homebridge-weather-plus/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/admin/Desktop/homebridge-weather-plus/apis/weatherunderground.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
```

**Comment by wimleers** [comment]
Oh my … it's been months since I did anything related to Homebridge, and I forgot one crucial step: to do `npm install` inside the cloned  `git` repo. 🙈 

But now I got something worse, a JS syntax error:
```
[12/29/2023, 10:33:41 PM] ERROR LOADING PLUGIN homebridge-weather-plus:
[12/29/2023, 10:33:41 PM] /Users/admin/Desktop/homebridge-weather-plus/util/converter.js:78
		sum += parseFloat(array[i];
		                         ^

SyntaxError: missing ) after argument list
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/admin/Desktop/homebridge-weather-plus/apis/weatherunderground.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
```

**Comment by wimleers** [comment]
That was a simple missing closing parenthesis (`)`) 👍 Once fixed, I got a JS logic error:
```
[12/29/2023, 10:35:26 PM] ERROR LOADING PLUGIN homebridge-weather-plus:
[12/29/2023, 10:35:26 PM] ReferenceError: getWetBulbTemperature is not defined
    at Object.<anonymous> (/Users/admin/Desktop/homebridge-weather-plus/util/converter.js:85:2)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/admin/Desktop/homebridge-weather-plus/apis/weatherunderground.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
```

**Comment by wimleers** [comment]
With these 2 small fixes, it works fine, @dacarson:
```
diff --git a/util/converter.js b/util/converter.js
index e604c79..56b25cd 100644
--- a/util/converter.js
+++ b/util/converter.js
@@ -75,14 +75,14 @@ const getRainAccumulated = function (array)
 	let sum = 0.0;
 	for (let i = 0; i < array.length; i++)
 	{
-		sum += parseFloat(array[i];
+		sum += parseFloat(array[i]);
 	}
 	return sum;
 };
 
 	// Calculate Wet Bulb Temperature
 	// @see https://www.omnicalculator.com/physics/wet-bulb
-	getWetBulbTemperature(dryBulbTemperature, relativeHumidity)
+	const getWetBulbTemperature = function (dryBulbTemperature, relativeHumidity)
 	{
 		let T = dryBulbTemperature;
 		let rh = relativeHumidity;
```

**Comment by dacarson** [comment]
Embarrassing. It certainly points to the fact that I need a better system of testing. I post the source code from one machine (Mac), but run HomeBridge on another (RaspberryPi). I test it on the Pi, and this time didn't copy all my changes back to the Mac. Ideally I would just have the Git repo on the Pi and develop, test, and submit from there, though my Pi is headless and VNC too painful to use. 
I landed the two changes you highlight above, as well as fix the indent of the getWetBulbTemperature function to match the rest of the file

**Comment by wimleers** [comment]
Been running cd653d3 for a week now, zero problems.

So: this is ready, let's get it merged 😊

**Comment by dacarson** [comment]
Thank you!

**Comment by wimleers** [comment]
Thanks! 😊

**Pull request merged**
