### PR TITLE
Additional API for Weewx

### PR DESCRIPTION
**Pull request by CHAMLEX**
In reference to #217 and #70 an additional API for Weewx weather integration was added.  I also added a sample JSON responese for testing.

### CODE REVIEW

**Comment by naofireblade** [comment]
Hi thanks for your PR! I cannot test this at the moment but as it seems not to break any existing functionality, I will gladly merge it. Could you provide some instructions how to use this in the readme?

**Comment by warenext** [comment]
Just curious... in the WeeWX JSON, characteristics which have units are broken out into arrays grouped according to the measurement system used.  I followed your lead in my contribution, but I was wondering why it's that way. Is it because WeeWX does the conversions itself, and all those values are already available?  Or because the developer of weewx-json handled it that that way?  The homebridge-weather-plus code has functions in characteristics.js for doing the unit conversions, and I think providing only one system of units in the JSON input and having weather-plus do the conversions would generally be more preferable.

**Comment by CHAMLEX** [comment]
I based the formatting off of the JSON response and the api reader on the Weather Underground JSON response and just included all the units that it would respond with.  You could format it to only use metric_si units, but I planned on using this JSON response with another application so I wanted to include the other units as well.  It also helped me to make sure I had everything coded correctly since I could make sure I was getting the correct units.

**Comment by ituri** [comment]
Really looking forward to this feature! 😊

**Comment by sinabuddy** [comment]
Today, i have tried to install and connect to weewx. weewx create the json-File.
But the homebridge shows no values. homebridge shows an error:

[10.5.2022, 18:34:03] [WeatherPlus] Error retrieving weather report and forecast
[10.5.2022, 18:34:03] [WeatherPlus] Error Message: Error: [
  {
    "error": {
      "code": "CDN-0001",
      "message": "Invalid apiKey."
    }
  }
] 

any ideas? 
am I too early? or too fast?
greatings

**Comment by CHAMLEX** [comment]
I don't believe this branch/edits has been incorporated yet.

**Comment by naofireblade** [comment]
Oh yes, I really need to merge and create a new release. Will do it this week.

**Pull request merged**
